<?php
/**
 * Render callback + caching for "custom/books-list" — lists every published
 * Book tagged with ONE Audience value (see book-cpt.php's
 * _bitesmart_book_audience). Placed once PER Audience group on the Books
 * page (post ID 2818, "Books and Links", real URL /learning/books/), each
 * instance picked via a "Audience" dropdown in the block editor — same
 * "one instance per X, picked from a dropdown" placement idiom as
 * custom/learning-search's Stage picker (see that block's own index.js/
 * learning-search.php).
 *
 * Redesigned 2026-08-30 from an earlier single-instance "auto-list
 * everything, grouped with baked-in headings" version — Janet's ask: the
 * per-group headings ("For Younger Children" etc.) needed to be FULLY
 * separate, ordinary Heading blocks she places/edits/reorders herself
 * directly on the page, not text generated by this block at all (even the
 * attribute-override version from earlier the same day still counted, in
 * her view, as "integrated with the block" — a non-coder shouldn't need to
 * open a block's Settings sidebar to find where a heading's wording lives).
 * Accepted trade-off, confirmed with Janet: a group's own auto-hide-when-
 * empty behavior is gone along with the baked-in heading — a group with
 * zero books now just renders an empty-state note (visible to editors only,
 * same posture as custom/learning-search's "choose a Stage" hint) rather
 * than a heading silently skipping itself; a plain Heading block has no way
 * to know whether its sibling block below it rendered anything.
 *
 * Cached, not regenerated on every page view — same generation-counter +
 * transient pattern as bitesmart_build_stage_card_list() (learning-search.php)
 * and bitesmart_build_downloads_page_card_list() (coloring-books-list.php).
 * Deliberately reuses THAT SAME shared counter (bitesmart_stage_cards_gen)
 * rather than inventing a new one — this file only READS the option
 * (get_option), so it has no load-order dependency on learning-search.php,
 * and adds its OWN bump hooks below (Book is no longer in
 * bitesmart_stage_cards_maybe_bump()'s list as of 2026-08-28, since it was
 * removed from the Learning Hub search/browse listing that function serves).
 */

/**
 * Cache-key ingredient covering the render TEMPLATE itself — same reasoning
 * as bitesmart_stage_cards_template_version() (learning-search.php) and
 * bitesmart_downloads_page_template_version() (coloring-books-list.php):
 * without this, editing render_book_block()/bitesmart_book_cover_gallery()
 * (book-display.php) or this file's own query logic would leave stale
 * rendered HTML sitting in cache indefinitely.
 *
 * @return string
 */
function bitesmart_books_list_template_version() {
    $files = array(
        __DIR__ . '/../book-display/book-display.php',
        __FILE__,
    );

    $stamps = array_map(
        function ( $file ) {
            return file_exists( $file ) ? filemtime( $file ) : 0;
        },
        $files
    );

    return implode( '-', $stamps );
}

/**
 * The 4 Audience values a block instance can be set to, in Janet's own
 * fixed order — used to populate the "Audience" dropdown in the block
 * editor (index.js, via this same list over the REST API — see that file)
 * and to validate/sanitize the stored attribute here. Labels here are
 * EDITOR-UI signage only ("which group is this instance showing") — they
 * are NOT rendered on the front end at all; the actual on-page heading text
 * is a real, separate Heading block Janet places herself. The Audience
 * field's own slug set is separately maintained in book-cpt.php's REST enum
 * and book-panel/index.js's RadioControl — see the comments on each of
 * those for why there's no single shared constant across the two plugins.
 * (As of 2026-08-31, Audience no longer drives a card badge at all — see
 * bitesmart_book_target_audience_badge() in book-display.php, a separate
 * freeform field with no fixed slug set of its own.)
 *
 * @return array<string, string> Audience meta value => editor-only label.
 */
function bitesmart_books_list_audience_groups() {
    return array(
        'younger_children' => __( 'Younger Children', 'custom-blocks' ),
        'older_children'   => __( 'Older Children', 'custom-blocks' ),
        'adult'            => __( 'Adults', 'custom-blocks' ),
        'all_ages'         => __( 'All Ages (With Guidance)', 'custom-blocks' ),
    );
}

/**
 * Build (or fetch from cache) every published Book tagged with ONE Audience
 * value's rendered card HTML, keyed by post ID (not a flat list) so
 * render_books_list_block() can apply the block's own manual 'order'
 * attribute (added 2026-08-30, per Janet — see that function's own comment)
 * afterward without a second query. Cached rows are alphabetical by title —
 * that's also the fallback order for any Book the editor hasn't manually
 * placed yet (a new Book, or one this Audience group's order list predates).
 *
 * @param string $audience_slug One of bitesmart_books_list_audience_groups()'s keys.
 * @param string $lang          Short language code (bitesmart_site_lang_code()) — part of the cache key only; card markup has translatable strings (badge labels, "Buy / More Info", etc.) that need a fresh cache per language.
 * @return array<int, string> Post ID => rendered card HTML, alphabetical by title.
 */
function bitesmart_build_books_list_cards( $audience_slug, $lang ) {
    $gen       = (int) get_option( 'bitesmart_stage_cards_gen', 1 );
    $cache_key = 'bitesmart_books_list_' . md5( $audience_slug . '|' . $lang . '|' . $gen . '|' . bitesmart_books_list_template_version() );

    $cached = get_transient( $cache_key );
    if ( is_array( $cached ) ) {
        return $cached;
    }

    // register_post_meta()'s 'default' => 'all_ages' (book-cpt.php) is an
    // application-layer fallback ONLY — get_post_meta() applies it, but
    // WP_Query's meta_query matches actual wp_postmeta rows and knows
    // nothing about it. A book with genuinely no stored row at all
    // (shouldn't happen once saved even once, but a never-saved-since-the-
    // field-existed row is a real possibility) would otherwise silently
    // match no Audience group's query — so the 'all_ages' group's query
    // ALSO matches "no row exists", mirroring get_post_meta()'s own default.
    $meta_query = ( 'all_ages' === $audience_slug )
        ? array(
            'relation' => 'OR',
            array( 'key' => '_bitesmart_book_audience', 'value' => 'all_ages', 'compare' => '=' ),
            array( 'key' => '_bitesmart_book_audience', 'compare' => 'NOT EXISTS' ),
        )
        : array(
            array( 'key' => '_bitesmart_book_audience', 'value' => $audience_slug, 'compare' => '=' ),
        );

    $query = new WP_Query( array(
        'post_type'      => 'book',
        'post_status'    => 'publish',
        'posts_per_page' => -1,
        'no_found_rows'  => true,
        'orderby'        => 'title',
        'order'          => 'ASC',
        'meta_query'     => $meta_query,
    ) );

    $cards = array();
    foreach ( $query->posts as $post ) {
        $html = render_book_block( array( 'bookId' => $post->ID ) );
        if ( $html ) {
            $cards[ $post->ID ] = $html;
        }
    }

    // Cached for up to a day as a safety net even if a bump somehow got
    // missed — the generation counter is what actually keeps this fresh in
    // the normal case (a new generation means a brand new cache key).
    set_transient( $cache_key, $cards, DAY_IN_SECONDS );

    return $cards;
}

/**
 * Bumps the shared bitesmart_stage_cards_gen counter (defined in
 * learning-search.php) whenever a Book is saved or permanently deleted.
 * TWO hooks, not one — save_post_book alone would miss a hard-deleted (not
 * trashed) book for up to a day, same two-hook pattern every other consumer
 * of this counter already uses (see bitesmart_stage_cards_maybe_bump() +
 * its own delete_post hook in learning-search.php). Calling
 * bitesmart_stage_cards_bump_generation() here (defined in a different file)
 * is safe regardless of require_once order — it only ever runs inside an
 * action callback fired long after every plugin file is loaded, not at
 * require-time.
 */
function bitesmart_books_list_maybe_bump( $post_id, $post = null ) {
    $post_type = $post ? $post->post_type : get_post_type( $post_id );
    if ( 'book' === $post_type ) {
        bitesmart_stage_cards_bump_generation();
    }
}
add_action( 'save_post_book', 'bitesmart_books_list_maybe_bump', 10, 2 );
add_action( 'delete_post', 'bitesmart_books_list_maybe_bump' );

/**
 * custom/books-list calls render_book_block() directly as a PHP function
 * (building cards from a WP_Query, not literal block markup), so WordPress's
 * automatic "scan the page's saved content for which blocks it uses, enqueue
 * their block.json assets" never detects custom/book as present — its
 * registered style AND (added 2026-08-29, for the "Inside the Book" preview
 * carousel) viewScript would otherwise silently never load on this page,
 * even though the HTML renders fine. Same footgun/fix already established in
 * learning-search.php's bitesmart_learning_search_enqueue_card_styles() —
 * see that function's own comment for the fuller "why".
 */
function bitesmart_books_list_enqueue_book_card_assets() {
    if ( ! function_exists( 'generate_block_asset_handle' ) || ! has_block( 'custom/books-list' ) ) {
        return;
    }

    $style_handle = generate_block_asset_handle( 'custom/book', 'style' );
    if ( wp_style_is( $style_handle, 'registered' ) ) {
        wp_enqueue_style( $style_handle );
    }

    $script_handle = generate_block_asset_handle( 'custom/book', 'viewScript' );
    if ( wp_script_is( $script_handle, 'registered' ) ) {
        wp_enqueue_script( $script_handle );
    }
}
add_action( 'wp_enqueue_scripts', 'bitesmart_books_list_enqueue_book_card_assets' );

/**
 * Applies this block instance's manual 'order' attribute (an array of Book
 * post IDs, set via the drag/reorder control in index.js — added 2026-08-30,
 * per Janet, so an editor can decide book order right on the Books page
 * itself) over $cards' own alphabetical-by-title order. Any ID in 'order'
 * that no longer matches a card (a book since unpublished, deleted, or
 * moved to a different Audience group) is silently skipped rather than
 * producing a gap. Any card NOT mentioned in 'order' — a newly published
 * book the editor hasn't placed yet, or every card when 'order' is empty —
 * is appended afterward in its existing alphabetical order, so a new book
 * always shows up somewhere without needing the page re-edited.
 *
 * @param array<int, string> $cards Post ID => rendered card HTML, from bitesmart_build_books_list_cards().
 * @param array<int, mixed>  $order Post IDs in the editor's chosen order (block attribute, may contain non-int/stale values).
 * @return array<int, string> Rendered card HTML, in final display order.
 */
function bitesmart_books_list_apply_order( array $cards, array $order ) {
    $ordered = array();
    $placed  = array();

    foreach ( $order as $id ) {
        $id = absint( $id );
        if ( isset( $cards[ $id ] ) && ! isset( $placed[ $id ] ) ) {
            $ordered[] = $cards[ $id ];
            $placed[ $id ] = true;
        }
    }

    foreach ( $cards as $id => $html ) {
        if ( ! isset( $placed[ $id ] ) ) {
            $ordered[] = $html;
        }
    }

    return $ordered;
}

/**
 * Makes one already-rendered card's cover image inert until Show More
 * actually reveals it — added 2026-08-31, per Janet: `display:none` alone
 * (the Show More/Show Less toggle's own mechanism) does NOT stop a real
 * `<img src>` from downloading immediately, since CSS display doesn't block
 * the fetch; every hidden card's cover was loading regardless of whether
 * anyone ever clicked Show More. Same "keep the real URL out of `src` until
 * actually needed" idea bitesmart_book_cover_gallery() (book-display.php)
 * already uses for preview-carousel slides, applied here to the one real
 * `<img>` a card always has (its cover) — read-more.js's expand() hydrates
 * `data-src` back into `src` the moment a group is actually opened (click or
 * hash deep-link), so a visitor who never clicks Show More never downloads
 * those covers at all.
 *
 * A narrow, anchored regex rather than a general HTML parse — safe here
 * specifically because this only ever runs against render_book_block()'s
 * own known output (this codebase's control, not arbitrary editor content;
 * see [[be-bitesmart-book-cpt-status]] in memory for why regex surgery on
 * REAL editor content bit this project once already, a different situation
 * from this one). Only the exact `class="book-gallery-image"` cover tag
 * matches — every other `src` elsewhere in a card's markup (there are none
 * today, but defensively) is left untouched.
 *
 * @param string $card_html One rendered card, from render_book_block().
 * @return string Same HTML, cover `src` renamed to `data-src`.
 */
function bitesmart_books_list_make_cover_lazy( $card_html ) {
    return preg_replace(
        '/(<img\s+class="book-gallery-image"\s+)src="([^"]*)"/',
        '$1data-src="$2"',
        $card_html,
        1 // one cover per card — never touch a second match.
    );
}

/**
 * Render callback for "custom/books-list". Renders ONLY the matching Books'
 * cards for this instance's chosen Audience — no heading, no intro text, no
 * grouping logic at all. An editor places a real Heading block above each
 * instance themselves (e.g. "For Younger Children" above the
 * younger_children instance) and edits/reorders/removes it exactly like any
 * other page content, fully independent of this block.
 */
function render_books_list_block( $attributes ) {
    $audience_slug = isset( $attributes['audience'] ) ? sanitize_key( $attributes['audience'] ) : '';
    $valid_slugs   = bitesmart_books_list_audience_groups();

    if ( ! isset( $valid_slugs[ $audience_slug ] ) ) {
        // No Audience chosen yet — only editors/admins see a hint on the
        // live page; ordinary visitors just see nothing, same posture as
        // custom/learning-search's own "choose a Stage" unconfigured state
        // (render_learning_search_block() in learning-search.php).
        if ( current_user_can( 'edit_posts' ) ) {
            return '<p class="books-list-unconfigured">' .
                esc_html__( 'Books List: choose an Audience group in the block settings.', 'custom-blocks' ) .
                '</p>';
        }
        return '';
    }

    $lang  = bitesmart_site_lang_code();
    $cards = bitesmart_build_books_list_cards( $audience_slug, $lang );

    $order = isset( $attributes['order'] ) && is_array( $attributes['order'] ) ? $attributes['order'] : array();
    $cards = bitesmart_books_list_apply_order( $cards, $order );

    ob_start();
    ?>
    <?php
    // Only the first (already-ordered) card shows by default — the rest sit
    // behind a Show More/Show Less toggle, added 2026-08-31 per Janet once
    // 4 groups on one page made the full list of every book feel too long.
    // Reuses read-more.js verbatim (already enqueued site-wide, already
    // handles multiple independent .expandable-article-block instances on
    // one page — see that file, and book-display.php's own Book Excerpt
    // toggle for the established div-based usage this mirrors) — no new JS
    // needed here, just the same markup shape. Custom
    // data-label-collapsed/-expanded (Janet's own wording, "Show More"/
    // "Show Less", not the shared script's "Read More"/"Read Less" default)
    // is exactly what those data attributes exist for (see read-more.js).
    // The wrapper's existing `id="books-list-{slug}"` (unchanged, was already
    // here for editor/CSS targeting) doubles as this section's link target —
    // a hyperlink to e.g. #books-list-older_children lands here, and
    // read-more.js's own hash-check (added the same day) finds the
    // .expandable-article-block nested inside and auto-opens it, so a parent
    // following that link always sees every book, not just the first.
    $first_card      = array_shift( $cards );
    $remaining_cards = $cards; // whatever's left after the shift, [] if only one book total.
    ?>
    <div id="books-list-<?php echo esc_attr( $audience_slug ); ?>" class="wp-block-custom-books-list wp-block-group">
        <?php if ( empty( $first_card ) ) : ?>
            <?php if ( current_user_can( 'edit_posts' ) ) : ?>
                <p class="books-list-empty"><?php esc_html_e( 'No Books are tagged with this Audience yet.', 'custom-blocks' ); ?></p>
            <?php endif; ?>
        <?php else : ?>
            <?php echo $first_card; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- already-escaped HTML from render_book_block() ?>
            <?php if ( ! empty( $remaining_cards ) ) : ?>
                <div class="expandable-article-block books-list-expandable">
                    <div class="expandable-content">
                        <?php foreach ( $remaining_cards as $card_html ) : ?>
                            <?php echo bitesmart_books_list_make_cover_lazy( $card_html ); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- already-escaped HTML from render_book_block(), only the cover's src->data-src attribute renamed ?>
                        <?php endforeach; ?>
                    </div>
                    <button
                        type="button"
                        class="read-more-toggle block-toggle-btn is-style-outline"
                        data-expanded="false"
                        data-label-collapsed="<?php echo esc_attr__( 'Show More', 'custom-blocks' ); ?>"
                        data-label-expanded="<?php echo esc_attr__( 'Show Less', 'custom-blocks' ); ?>"
                    ><?php esc_html_e( 'Show More', 'custom-blocks' ); ?></button>
                </div>
            <?php endif; ?>
        <?php endif; ?>
    </div>
    <?php
    return ob_get_clean();
}
