<?php
/**
 * The guide's actual 68 citations, pasted by Janet mid-implementation
 * 2026-08-16 — see citation-cpt.php's bitesmart_seed_citations() for how
 * this data actually gets turned into real Citation posts (a one-time,
 * Janet-triggered import, not an automatic one — see that function's own
 * comment for why).
 *
 * One entry per NUMBERED SLOT in the source document, 1–68 — NOT one
 * entry per unique underlying source. The source document assigns a fresh
 * number to a source every time it's cited, even if the exact same source
 * was already cited under an earlier number (e.g. #2, #14, #34, and #67
 * are all the identical Gilchrist et al. reference) — kept exactly that
 * way here rather than deduplicated, since each number is its own
 * independently-citable slot a chapter's "Cite" tool can point at
 * (see [[be-bitesmart-guide-cpt-plan]] in memory for the full feature).
 *
 * REVISED 2026-08-16 — the original version of this file only kept the
 * HTML link (as a single generic `url` field) and dropped Janet's DOI and
 * PDF fields entirely; she caught this ("There were DIO, HTML and PDF
 * fields, some of which had urls some had information like not
 * available"). This version captures all three exactly as pasted: `doi`
 * and `pdf` are frequently NOT urls at all (e.g. "Not available", "Not
 * applicable", "Subscription / institutional access", "Varies by
 * article") — kept as plain text rather than forced into a url shape;
 * citation-cpt.php decides at render time whether a given value is
 * actually a clickable link.
 *
 * @return array<int, array{number: int, text: string, doi: string, html: string, pdf: string}>
 */
function bitesmart_citation_seed_data() {
    return array(
        array( 'number' => 1, 'text' => 'Centers for Disease Control and Prevention (CDC). <em>Nonfatal Dog Bite&ndash;Related Injuries Treated in Hospital Emergency Departments &mdash; United States, 2001</em>.', 'doi' => 'Not available', 'html' => 'https://www.cdc.gov/mmwr/preview/mmwrhtml/mm5226a1.htm', 'pdf' => 'https://www.cdc.gov/mmwr/pdf/wk/mm5226.pdf' ),
        array( 'number' => 2, 'text' => 'Gilchrist J, Sacks JJ, White D, Kresnow MJ. <em>Dog bites: still a problem?</em> Injury Prevention. 2008;14(5):296&ndash;301.', 'doi' => 'https://doi.org/10.1136/ip.2007.016220', 'html' => 'https://injuryprevention.bmj.com/content/14/5/296', 'pdf' => 'https://injuryprevention.bmj.com/content/injuryprev/14/5/296.full.pdf' ),
        array( 'number' => 3, 'text' => 'World Health Organization (WHO). <em>Rabies Fact Sheet</em>.', 'doi' => 'Not available', 'html' => 'https://www.who.int/news-room/fact-sheets/detail/rabies', 'pdf' => 'https://www.who.int/docs/default-source/documents/rabies-fact-sheet.pdf' ),
        array( 'number' => 4, 'text' => 'Hampson K, Coudeville L, Lembo T, et al. <em>Estimating the global burden of endemic canine rabies</em>. PLOS Neglected Tropical Diseases. 2015;9(4):e0003709.', 'doi' => 'https://doi.org/10.1371/journal.pntd.0003709', 'html' => 'https://journals.plos.org/plosntds/article?id=10.1371/journal.pntd.0003709', 'pdf' => 'https://journals.plos.org/plosntds/article/file?id=10.1371/journal.pntd.0003709&type=printable' ),
        array( 'number' => 5, 'text' => 'Reisner IR, Nance ML, Zeller JS, Houseknecht EM, Kassam-Adams N, Wiebe DJ. <em>Behavioural characteristics associated with dog bites to children</em>. Injury Prevention.', 'doi' => 'https://doi.org/10.1136/ip.2010.030742', 'html' => 'https://injuryprevention.bmj.com/content/17/5/348', 'pdf' => 'https://injuryprevention.bmj.com/content/injuryprev/17/5/348.full.pdf' ),
        array( 'number' => 6, 'text' => 'American Veterinary Medical Association (AVMA). <em>Dog Bite Prevention</em>.', 'doi' => 'Not available', 'html' => 'https://www.avma.org/resources-tools/pet-owners/dog-bite-prevention', 'pdf' => 'https://www.avma.org/sites/default/files/2020-03/dogbite.pdf' ),
        array( 'number' => 7, 'text' => 'Dodman NH, Brown DC. <em>Serotonin, aggression, and stress in dogs</em>. Veterinary Clinics of North America: Small Animal Practice.', 'doi' => 'https://doi.org/10.1016/j.cvsm.2016.01.001', 'html' => 'https://www.sciencedirect.com/science/article/pii/S019556161600002X', 'pdf' => 'Subscription / institutional access' ),
        array( 'number' => 8, 'text' => 'Overall KL. <em>Manual of Clinical Behavioral Medicine for Dogs and Cats</em>. Elsevier.', 'doi' => 'Not applicable', 'html' => 'https://www.elsevier.com/books/manual-of-clinical-behavioral-medicine-for-dogs-and-cats/overall/9780323240658', 'pdf' => 'Not publicly available' ),
        array( 'number' => 9, 'text' => 'Reisner IR, Nance ML, Zeller JS, Houseknecht EM, Kassam-Adams N, Wiebe DJ. <em>Behavioural characteristics associated with dog bites to children</em>. Injury Prevention.', 'doi' => 'https://doi.org/10.1136/ip.2010.030742', 'html' => 'https://injuryprevention.bmj.com/content/17/5/348', 'pdf' => 'https://injuryprevention.bmj.com/content/injuryprev/17/5/348.full.pdf' ),
        array( 'number' => 10, 'text' => 'Messam LLMV, Kass PH, Chomel BB, Hart LA. <em>Factors associated with bites to a child from a dog living in the same home</em>. Frontiers in Veterinary Science. 2018.', 'doi' => 'https://doi.org/10.3389/fvets.2018.00066', 'html' => 'https://www.frontiersin.org/articles/10.3389/fvets.2018.00066/full', 'pdf' => 'https://www.frontiersin.org/articles/10.3389/fvets.2018.00066/pdf' ),
        array( 'number' => 11, 'text' => 'American Academy of Pediatrics (AAP). <em>Dog Bite Prevention Tips</em>.', 'doi' => 'Not available', 'html' => 'https://www.healthychildren.org/English/safety-prevention/all-around/Pages/Dog-Bite-Prevention-Tips.aspx', 'pdf' => 'Not available' ),
        array( 'number' => 12, 'text' => 'American Academy of Pediatrics (AAP). <em>Prevention of Dog Bites in Children</em>. Pediatrics.', 'doi' => 'https://doi.org/10.1542/peds.2012-2552', 'html' => 'https://publications.aap.org/pediatrics/article/130/6/e1647/30983', 'pdf' => 'https://publications.aap.org/pediatrics/article-pdf/130/6/e1647/1060367/peds_2012-2552.pdf' ),
        array( 'number' => 13, 'text' => 'Reisner IR, Nance ML, Zeller JS, Houseknecht EM, Kassam-Adams N, Wiebe DJ. <em>Behavioural characteristics associated with dog bites to children</em>. Injury Prevention.', 'doi' => 'https://doi.org/10.1136/ip.2010.030742', 'html' => 'https://injuryprevention.bmj.com/content/17/5/348', 'pdf' => 'https://injuryprevention.bmj.com/content/injuryprev/17/5/348.full.pdf' ),
        array( 'number' => 14, 'text' => 'Gilchrist J, Sacks JJ, White D, Kresnow MJ. <em>Dog bites: still a problem?</em> Injury Prevention. 2008;14(5):296&ndash;301.', 'doi' => 'https://doi.org/10.1136/ip.2007.016220', 'html' => 'https://injuryprevention.bmj.com/content/14/5/296', 'pdf' => 'https://injuryprevention.bmj.com/content/injuryprev/14/5/296.full.pdf' ),
        array( 'number' => 15, 'text' => 'Messam LLMV, Kass PH, Chomel BB, Hart LA. <em>Factors associated with bites to a child from a dog living in the same home</em>. Frontiers in Veterinary Science. 2018.', 'doi' => 'https://doi.org/10.3389/fvets.2018.00066', 'html' => 'https://www.frontiersin.org/articles/10.3389/fvets.2018.00066/full', 'pdf' => 'https://www.frontiersin.org/articles/10.3389/fvets.2018.00066/pdf' ),
        array( 'number' => 16, 'text' => 'American Veterinary Medical Association (AVMA). <em>Dog Bite Prevention</em>.', 'doi' => 'Not available', 'html' => 'https://www.avma.org/resources-tools/pet-owners/dog-bite-prevention', 'pdf' => 'https://www.avma.org/sites/default/files/2020-03/dogbite.pdf' ),
        array( 'number' => 17, 'text' => 'World Health Organization (WHO) / UNICEF. <em>World Report on Child Injury Prevention</em>.', 'doi' => 'Not available', 'html' => 'https://www.who.int/publications/i/item/9789241563574', 'pdf' => 'https://apps.who.int/iris/bitstream/handle/10665/43851/9789241563574_eng.pdf' ),
        array( 'number' => 18, 'text' => 'American Academy of Pediatrics (AAP). <em>Dog Bite Prevention Tips</em>.', 'doi' => 'Not available', 'html' => 'https://www.healthychildren.org/English/safety-prevention/all-around/Pages/Dog-Bite-Prevention-Tips.aspx', 'pdf' => 'Not available' ),
        array( 'number' => 19, 'text' => 'Centers for Disease Control and Prevention (CDC). <em>Injury Prevention & Control</em>.', 'doi' => 'Not applicable', 'html' => 'https://www.cdc.gov/injury/index.html', 'pdf' => 'Not applicable' ),
        array( 'number' => 20, 'text' => 'World Health Organization (WHO) / UNICEF. <em>World Report on Child Injury Prevention</em>.', 'doi' => 'Not available', 'html' => 'https://www.who.int/publications/i/item/9789241563574', 'pdf' => 'https://apps.who.int/iris/bitstream/handle/10665/43851/9789241563574_eng.pdf' ),
        array( 'number' => 21, 'text' => 'Overall KL. <em>Manual of Clinical Behavioral Medicine for Dogs and Cats</em>. Elsevier.', 'doi' => 'Not applicable', 'html' => 'https://www.elsevier.com/books/manual-of-clinical-behavioral-medicine-for-dogs-and-cats/overall/9780323240658', 'pdf' => 'Not publicly available' ),
        array( 'number' => 22, 'text' => 'Dodman NH, Brown DC. <em>Serotonin, aggression, and stress in dogs</em>. Veterinary Clinics of North America: Small Animal Practice.', 'doi' => 'https://doi.org/10.1016/j.cvsm.2016.01.001', 'html' => 'https://www.sciencedirect.com/science/article/pii/S019556161600002X', 'pdf' => 'Subscription / institutional access' ),
        array( 'number' => 23, 'text' => 'Messam LLMV, Kass PH, Chomel BB, Hart LA. <em>Factors associated with bites to a child from a dog living in the same home</em>. Frontiers in Veterinary Science. 2018.', 'doi' => 'https://doi.org/10.3389/fvets.2018.00066', 'html' => 'https://www.frontiersin.org/articles/10.3389/fvets.2018.00066/full', 'pdf' => 'https://www.frontiersin.org/articles/10.3389/fvets.2018.00066/pdf' ),
        array( 'number' => 24, 'text' => 'Overall KL. <em>Manual of Clinical Behavioral Medicine for Dogs and Cats</em>. Elsevier.', 'doi' => 'Not applicable', 'html' => 'https://www.elsevier.com/books/manual-of-clinical-behavioral-medicine-for-dogs-and-cats/overall/9780323240658', 'pdf' => 'Not publicly available' ),
        array( 'number' => 25, 'text' => 'Dodman NH, Brown DC. <em>Serotonin, aggression, and stress in dogs</em>. Veterinary Clinics of North America: Small Animal Practice.', 'doi' => 'https://doi.org/10.1016/j.cvsm.2016.01.001', 'html' => 'https://www.sciencedirect.com/science/article/pii/S019556161600002X', 'pdf' => 'Subscription / institutional access' ),
        array( 'number' => 26, 'text' => 'Reisner IR, Nance ML, Zeller JS, Houseknecht EM, Kassam-Adams N, Wiebe DJ. <em>Behavioural characteristics associated with dog bites to children</em>. Injury Prevention.', 'doi' => 'https://doi.org/10.1136/ip.2010.030742', 'html' => 'https://injuryprevention.bmj.com/content/17/5/348', 'pdf' => 'https://injuryprevention.bmj.com/content/injuryprev/17/5/348.full.pdf' ),
        array( 'number' => 27, 'text' => 'Messam LLMV, Kass PH, Chomel BB, Hart LA. <em>Factors associated with bites to a child from a dog living in the same home</em>. Frontiers in Veterinary Science. 2018.', 'doi' => 'https://doi.org/10.3389/fvets.2018.00066', 'html' => 'https://www.frontiersin.org/articles/10.3389/fvets.2018.00066/full', 'pdf' => 'https://www.frontiersin.org/articles/10.3389/fvets.2018.00066/pdf' ),
        array( 'number' => 28, 'text' => 'American Veterinary Medical Association (AVMA). <em>Dog Bite Prevention</em>.', 'doi' => 'Not available', 'html' => 'https://www.avma.org/resources-tools/pet-owners/dog-bite-prevention', 'pdf' => 'https://www.avma.org/sites/default/files/2020-03/dogbite.pdf' ),
        array( 'number' => 29, 'text' => 'American Academy of Pediatrics (AAP). <em>Prevention of Dog Bites in Children</em>. Pediatrics.', 'doi' => 'https://doi.org/10.1542/peds.2012-2552', 'html' => 'https://publications.aap.org/pediatrics/article/130/6/e1647/30983', 'pdf' => 'https://publications.aap.org/pediatrics/article-pdf/130/6/e1647/1060367/peds_2012-2552.pdf' ),
        array( 'number' => 30, 'text' => 'American Veterinary Medical Association (AVMA). <em>Dog Bite Prevention</em>.', 'doi' => 'Not available', 'html' => 'https://www.avma.org/resources-tools/pet-owners/dog-bite-prevention', 'pdf' => 'https://www.avma.org/sites/default/files/2020-03/dogbite.pdf' ),
        array( 'number' => 31, 'text' => 'Messam LLMV, Kass PH, Chomel BB, Hart LA. <em>Factors associated with bites to a child from a dog living in the same home</em>. Frontiers in Veterinary Science. 2018.', 'doi' => 'https://doi.org/10.3389/fvets.2018.00066', 'html' => 'https://www.frontiersin.org/articles/10.3389/fvets.2018.00066/full', 'pdf' => 'https://www.frontiersin.org/articles/10.3389/fvets.2018.00066/pdf' ),
        array( 'number' => 32, 'text' => 'American Academy of Pediatrics (AAP). <em>Prevention of Dog Bites in Children</em>. Pediatrics.', 'doi' => 'https://doi.org/10.1542/peds.2012-2552', 'html' => 'https://publications.aap.org/pediatrics/article/130/6/e1647/30983', 'pdf' => 'https://publications.aap.org/pediatrics/article-pdf/130/6/e1647/1060367/peds_2012-2552.pdf' ),
        array( 'number' => 33, 'text' => 'National Institutes of Health (NIH) / PubMed Central. <em>Dog Bite Injuries in Children &mdash; Clinical and Epidemiological Studies</em>.', 'doi' => 'Varies by article', 'html' => 'https://www.ncbi.nlm.nih.gov/pmc/', 'pdf' => 'Available per article' ),
        array( 'number' => 34, 'text' => 'Gilchrist J, Sacks JJ, White D, Kresnow MJ. <em>Dog bites: still a problem?</em> Injury Prevention. 2008;14(5):296&ndash;301.', 'doi' => 'https://doi.org/10.1136/ip.2007.016220', 'html' => 'https://injuryprevention.bmj.com/content/14/5/296', 'pdf' => 'https://injuryprevention.bmj.com/content/injuryprev/14/5/296.full.pdf' ),
        array( 'number' => 35, 'text' => 'American Academy of Pediatrics (AAP). <em>Prevention of Dog Bites in Children</em>. Pediatrics.', 'doi' => 'https://doi.org/10.1542/peds.2012-2552', 'html' => 'https://publications.aap.org/pediatrics/article/130/6/e1647/30983', 'pdf' => 'https://publications.aap.org/pediatrics/article-pdf/130/6/e1647/1060367/peds_2012-2552.pdf' ),
        array( 'number' => 36, 'text' => 'National Institutes of Health (NIH) / PubMed Central. <em>Dog Bite Injuries in Children &mdash; Clinical and Epidemiological Studies</em>.', 'doi' => 'Varies by article', 'html' => 'https://www.ncbi.nlm.nih.gov/pmc/', 'pdf' => 'Available per article' ),
        array( 'number' => 37, 'text' => 'World Health Organization (WHO) / UNICEF. <em>World Report on Child Injury Prevention</em>.', 'doi' => 'Not available', 'html' => 'https://www.who.int/publications/i/item/9789241563574', 'pdf' => 'https://apps.who.int/iris/bitstream/handle/10665/43851/9789241563574_eng.pdf' ),
        array( 'number' => 38, 'text' => 'Insurance Information Institute / State Farm. <em>Dog-related injury claim payouts hit $1.12 billion in 2023</em>.', 'doi' => 'Not available', 'html' => 'https://www.iii.org/press-release/triple-i-dog-related-injury-claim-payouts-hit-112-billion-in-2023-040824', 'pdf' => 'Not available' ),
        array( 'number' => 39, 'text' => 'Centers for Disease Control and Prevention (CDC). <em>Nonfatal Dog Bite&ndash;Related Injuries Treated in Hospital Emergency Departments &mdash; United States, 2001</em>.', 'doi' => 'Not available', 'html' => 'https://www.cdc.gov/mmwr/preview/mmwrhtml/mm5226a1.htm', 'pdf' => 'https://www.cdc.gov/mmwr/pdf/wk/mm5226.pdf' ),
        array( 'number' => 40, 'text' => 'Centers for Disease Control and Prevention (CDC). <em>Injury Prevention & Control</em>.', 'doi' => 'Not applicable', 'html' => 'https://www.cdc.gov/injury/index.html', 'pdf' => 'Not applicable' ),
        array( 'number' => 41, 'text' => 'American Bar Association (ABA). <em>Tort Trial & Insurance Practice Section &mdash; Animal Law Resources</em>.', 'doi' => 'Not applicable', 'html' => 'https://www.americanbar.org/groups/tort_trial_insurance_practice/resources/', 'pdf' => 'Not applicable' ),
        array( 'number' => 42, 'text' => 'Insurance Information Institute / State Farm. <em>Dog-related injury claim payouts hit $1.12 billion in 2023</em>.', 'doi' => 'Not available', 'html' => 'https://www.iii.org/press-release/triple-i-dog-related-injury-claim-payouts-hit-112-billion-in-2023-040824', 'pdf' => 'Not available' ),
        array( 'number' => 43, 'text' => 'World Health Organization (WHO) / UNICEF. <em>World Report on Child Injury Prevention</em>.', 'doi' => 'Not available', 'html' => 'https://www.who.int/publications/i/item/9789241563574', 'pdf' => 'https://apps.who.int/iris/bitstream/handle/10665/43851/9789241563574_eng.pdf' ),
        array( 'number' => 44, 'text' => 'Centers for Disease Control and Prevention (CDC). <em>Prevent Dog Bites</em>.', 'doi' => 'Not available', 'html' => 'https://www.cdc.gov/healthypets/pets/dogs/prevent-dog-bites.html', 'pdf' => 'Not available' ),
        array( 'number' => 45, 'text' => 'American Veterinary Medical Association (AVMA). <em>Dog Bite Prevention</em>.', 'doi' => 'Not available', 'html' => 'https://www.avma.org/resources-tools/pet-owners/dog-bite-prevention', 'pdf' => 'https://www.avma.org/sites/default/files/2020-03/dogbite.pdf' ),
        array( 'number' => 46, 'text' => 'American Academy of Pediatrics (AAP). <em>Prevention of Dog Bites in Children</em>. Pediatrics.', 'doi' => 'https://doi.org/10.1542/peds.2012-2552', 'html' => 'https://publications.aap.org/pediatrics/article/130/6/e1647/30983', 'pdf' => 'https://publications.aap.org/pediatrics/article-pdf/130/6/e1647/1060367/peds_2012-2552.pdf' ),
        array( 'number' => 47, 'text' => 'Overall KL. <em>Manual of Clinical Behavioral Medicine for Dogs and Cats</em>. Elsevier.', 'doi' => 'Not applicable', 'html' => 'https://www.elsevier.com/books/manual-of-clinical-behavioral-medicine-for-dogs-and-cats/overall/9780323240658', 'pdf' => 'Not publicly available' ),
        array( 'number' => 48, 'text' => 'Dodman NH, Brown DC. <em>Serotonin, aggression, and stress in dogs</em>. Veterinary Clinics of North America: Small Animal Practice.', 'doi' => 'https://doi.org/10.1016/j.cvsm.2016.01.001', 'html' => 'https://www.sciencedirect.com/science/article/pii/S019556161600002X', 'pdf' => 'Subscription / institutional access' ),
        array( 'number' => 49, 'text' => 'World Health Organization (WHO). <em>Rabies Fact Sheet</em>.', 'doi' => 'Not available', 'html' => 'https://www.who.int/news-room/fact-sheets/detail/rabies', 'pdf' => 'https://www.who.int/docs/default-source/documents/rabies-fact-sheet.pdf' ),
        array( 'number' => 50, 'text' => 'Hampson K, Coudeville L, Lembo T, et al. <em>Estimating the global burden of endemic canine rabies</em>. PLOS Neglected Tropical Diseases. 2015;9(4):e0003709.', 'doi' => 'https://doi.org/10.1371/journal.pntd.0003709', 'html' => 'https://journals.plos.org/plosntds/article?id=10.1371/journal.pntd.0003709', 'pdf' => 'https://journals.plos.org/plosntds/article/file?id=10.1371/journal.pntd.0003709&type=printable' ),
        array( 'number' => 51, 'text' => 'World Health Organization (WHO) / UNICEF. <em>World Report on Child Injury Prevention</em>.', 'doi' => 'Not available', 'html' => 'https://www.who.int/publications/i/item/9789241563574', 'pdf' => 'https://apps.who.int/iris/bitstream/handle/10665/43851/9789241563574_eng.pdf' ),
        array( 'number' => 52, 'text' => 'American Academy of Pediatrics (AAP). <em>Dog Bite Prevention Tips</em>.', 'doi' => 'Not available', 'html' => 'https://www.healthychildren.org/English/safety-prevention/all-around/Pages/Dog-Bite-Prevention-Tips.aspx', 'pdf' => 'Not available' ),
        array( 'number' => 53, 'text' => 'Centers for Disease Control and Prevention (CDC). <em>Injury Prevention & Control</em>.', 'doi' => 'Not applicable', 'html' => 'https://www.cdc.gov/injury/index.html', 'pdf' => 'Not applicable' ),
        array( 'number' => 54, 'text' => 'American Veterinary Medical Association (AVMA). <em>Dog Bite Prevention</em>.', 'doi' => 'Not available', 'html' => 'https://www.avma.org/resources-tools/pet-owners/dog-bite-prevention', 'pdf' => 'https://www.avma.org/sites/default/files/2020-03/dogbite.pdf' ),
        array( 'number' => 55, 'text' => 'World Health Organization (WHO) / UNICEF. <em>World Report on Child Injury Prevention</em>.', 'doi' => 'Not available', 'html' => 'https://www.who.int/publications/i/item/9789241563574', 'pdf' => 'https://apps.who.int/iris/bitstream/handle/10665/43851/9789241563574_eng.pdf' ),
        array( 'number' => 56, 'text' => 'American Academy of Pediatrics (AAP). <em>Dog Bite Prevention Tips</em>.', 'doi' => 'Not available', 'html' => 'https://www.healthychildren.org/English/safety-prevention/all-around/Pages/Dog-Bite-Prevention-Tips.aspx', 'pdf' => 'Not available' ),
        array( 'number' => 57, 'text' => 'Centers for Disease Control and Prevention (CDC). <em>Prevent Dog Bites</em>.', 'doi' => 'Not available', 'html' => 'https://www.cdc.gov/healthypets/pets/dogs/prevent-dog-bites.html', 'pdf' => 'Not available' ),
        array( 'number' => 58, 'text' => 'American Academy of Pediatrics (AAP). <em>Dog Bite Prevention Tips</em>.', 'doi' => 'Not available', 'html' => 'https://www.healthychildren.org/English/safety-prevention/all-around/Pages/Dog-Bite-Prevention-Tips.aspx', 'pdf' => 'Not available' ),
        array( 'number' => 59, 'text' => 'American Veterinary Medical Association (AVMA). <em>Dog Bite Prevention</em>.', 'doi' => 'Not available', 'html' => 'https://www.avma.org/resources-tools/pet-owners/dog-bite-prevention', 'pdf' => 'https://www.avma.org/sites/default/files/2020-03/dogbite.pdf' ),
        array( 'number' => 60, 'text' => 'American Academy of Pediatrics (AAP). <em>Dog Bite Prevention Tips</em>.', 'doi' => 'Not available', 'html' => 'https://www.healthychildren.org/English/safety-prevention/all-around/Pages/Dog-Bite-Prevention-Tips.aspx', 'pdf' => 'Not available' ),
        array( 'number' => 61, 'text' => 'World Health Organization (WHO) / UNICEF. <em>World Report on Child Injury Prevention</em>.', 'doi' => 'Not available', 'html' => 'https://www.who.int/publications/i/item/9789241563574', 'pdf' => 'https://apps.who.int/iris/bitstream/handle/10665/43851/9789241563574_eng.pdf' ),
        array( 'number' => 62, 'text' => 'World Health Organization (WHO) / UNICEF. <em>World Report on Child Injury Prevention</em>.', 'doi' => 'Not available', 'html' => 'https://www.who.int/publications/i/item/9789241563574', 'pdf' => 'https://apps.who.int/iris/bitstream/handle/10665/43851/9789241563574_eng.pdf' ),
        array( 'number' => 63, 'text' => 'Centers for Disease Control and Prevention (CDC). <em>Injury Prevention & Control</em>.', 'doi' => 'Not applicable', 'html' => 'https://www.cdc.gov/injury/index.html', 'pdf' => 'Not applicable' ),
        array( 'number' => 64, 'text' => 'World Health Organization (WHO). <em>Rabies Fact Sheet</em>.', 'doi' => 'Not available', 'html' => 'https://www.who.int/news-room/fact-sheets/detail/rabies', 'pdf' => 'https://www.who.int/docs/default-source/documents/rabies-fact-sheet.pdf' ),
        array( 'number' => 65, 'text' => 'Hampson K, Coudeville L, Lembo T, et al. <em>Estimating the global burden of endemic canine rabies</em>. PLOS Neglected Tropical Diseases. 2015;9(4):e0003709.', 'doi' => 'https://doi.org/10.1371/journal.pntd.0003709', 'html' => 'https://journals.plos.org/plosntds/article?id=10.1371/journal.pntd.0003709', 'pdf' => 'https://journals.plos.org/plosntds/article/file?id=10.1371/journal.pntd.0003709&type=printable' ),
        array( 'number' => 66, 'text' => 'World Health Organization (WHO) / UNICEF. <em>World Report on Child Injury Prevention</em>.', 'doi' => 'Not available', 'html' => 'https://www.who.int/publications/i/item/9789241563574', 'pdf' => 'https://apps.who.int/iris/bitstream/handle/10665/43851/9789241563574_eng.pdf' ),
        array( 'number' => 67, 'text' => 'Gilchrist J, Sacks JJ, White D, Kresnow MJ. <em>Dog bites: still a problem?</em> Injury Prevention. 2008;14(5):296&ndash;301.', 'doi' => 'https://doi.org/10.1136/ip.2007.016220', 'html' => 'https://injuryprevention.bmj.com/content/14/5/296', 'pdf' => 'https://injuryprevention.bmj.com/content/injuryprev/14/5/296.full.pdf' ),
        array( 'number' => 68, 'text' => 'American Academy of Pediatrics (AAP). <em>Prevention of Dog Bites in Children</em>. Pediatrics.', 'doi' => 'https://doi.org/10.1542/peds.2012-2552', 'html' => 'https://publications.aap.org/pediatrics/article/130/6/e1647/30983', 'pdf' => 'https://publications.aap.org/pediatrics/article-pdf/130/6/e1647/1060367/peds_2012-2552.pdf' ),
    );
}
